# Generated by Django 5.0.1 on 2024-01-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sohalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Sohalar',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=140)),
                ('test', models.CharField(max_length=100)),
                ('a', models.CharField(blank=True, max_length=50, null=True)),
                ('b', models.CharField(blank=True, max_length=50, null=True)),
                ('c', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=50, null=True)),
                ('correct_answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('soha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sohalar')),
            ],
            options={
                'verbose_name_plural': 'Testlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
